#==============================================================================
# %% FILES TO LOAD -CAN BE EDITED
#==============================================================================
#These files are attached, retiga.yml is a detector configuration file
#The near field detector was already calibrated

#A materials file, is a cPickle file which contains material information like lattice
#parameters necessary for the reconstruction

analysis_name: NF_vol1

main_dir: /PATH/NF_reconstruction #working directory path
output_dir: /PATH/NF_output #defaults to main_dir

input_files:
  det_file: retiga.yml
  mat_file: materials.h5
  grain_out_file: /PATH/grains.out

experiment:
  beam_energy: 71.667
  mat_name: LSHR

  ome_start: 0.
  ome_end: 359.75  # degrees

  max_thh: None #number in degrees or None

  #optional
  # comp_thresh: 0.8
  # chi2_thresh: 0.05

  #you really don't want to be doing this... -REL
  # misorientation:
  #   use_misorientation: False
  #   bnd: 0.0  # degrees
  #   spacing: 0.25  # degrees, doesn't matter if bnd is 0
tomography:
  data_folder: /PATH/tomo_directory
  img_stem: nf_
  num_digits: 6
  bright:
    folder: /PATH/bright_field_images/ #defaults to data_folder
    img_start: 52
    num_imgs: 10
  dark:
    folder: /PATH/dark_field_images/ #defaults to data_folder
    img_start: 68
    num_imgs: 10
  images:
    img_start: 84
    num_imgs: 360
  ome_start: 0.0 #degrees
  ome_end: 359.75

  #Don't change these unless you know what you are doing, this will close small holes
  #and remove noise
  processing:
    recon_thresh: 0.0002 #usually varies between 0.0001 and 0.0005
    noise_obj_size: 500
    min_hole_size: 500
    erosion_iter: 1
    dilation_iter: 1

  reconstruction:
    project_single_layer: False #True projects the center layers through the volume
    cross_sectional_dim: 1.35 #cross sectional to reconstruct (should be at least 20%-30% over sample width)
    voxel_spacing: 0.005 #in mm
    v_bnds: [-0.4,0.4]



images:
  data_folder: /PATH/image_directory
  stem: nf_
  num_digits: 6
  img_start: 6
  nframes: 1440
  processing:
    num_for_dark: 250  # num images to use for median data
    img_threshold: 0
    method:
      # gaussian:
      #   sigma: 2.0
      #   size: 3.0
      dilations_only:
        num_erosions: 2 #num iterations of images erosion, don't mess with unless you know what you're doing
        num_dilations: 3 #num iterations of images erosion, don't mess with unless you know what you're doing
    ome_dilation_iter: 1

reconstruction:
  tomography:
    use_mask: True #True for using tomo, False for not using tomo
    mask_data_file: /PATH/tomo_mask.npz
    mask_vert_offset: -0.3 #offset between tomo and nf layer position

  cross_sectional_dim: 1.35
  voxel_spacing: 0.005  #mm, cubic voxel size for reconstruction
  v_bnds: [-0.085, 0.085] #mm, if bounds are equal, a single layer is produced

  beam_stop_y_cen: 0.0  # mm, measured from the origin of the detector paramters
  beam_stop_width: 0.6  # mm, width of the beam stop vertically

multiprocessing:
  num_cpus: -1 #number of processors, can use -1 or all
  # chunksize for multiprocessing, don't mess with unless you know what you're doing
  chunk_size: 500
  RAM_set: True  # if True, manually set max amount of ram
  max_RAM: 256  # only used if RAM_set is true. in GB
  # check: None
  # limit: None
  # generate: None

output_plot_check: True
